### ISSUE TITLE
Sort search results by where in the word the match is

### ISSUE THREAD

**Issue by haakontk** [lekoala/bootstrap5-autocomplete#19]
I'm using bootstrap5-autocomplete with my items grouped, and it works perfectly. Specifically it searches among hundreds of medical drugs from a remote .json file. However, the search results are in my opinion sorted in a suboptimal manner. 

For example if I try to search for the drug 'Eliquis' by entering 'Eli' in the input field then 'Anagrelide Bluefish', 'Aspaveli', 'Defitelio', etc, will show up before 'Eliquis'. Is there any way to prioritize drugs that have a complete match early on in the drug name so that 'Eliquis' shows up first? A parameter like `data-prioritize-match-start` or something would be perfect.

**Comment by haakontk** [comment]
Alternatively, a parameter like `data-startswith` so that the search results have to start with the input word.

For example "Eli" in the input field would give "Eliquis" and "Elidel" as results, but not 'Anagrelide'. Is this possible to accomplish?

Best regards.

**Comment by lekoala** [comment]
@haakontk sorting is tricky, and with groups it gets even worse
but the startsWith feature was easy to do, so i added it :)
https://github.com/lekoala/bootstrap5-autocomplete/releases/tag/1.1.17

otherwise, you might as well use the serverReponse callback and sort it yourself, or get data from a server backend sorted the way you want

**Comment by haakontk** [comment]
Great, thanks! I appreciate it.
