### ISSUE TITLE
Feature Request: Tab for Autocomplete

### ISSUE THREAD

**Issue by bwhartlove** [lekoala/bootstrap5-autocomplete#51]
Thank you for all the work on the bootstrap5-autocomplete project!

While working with the library, I noticed that using `Enter` will trigger an autocomplete, but `Tab` does not have the same behavior. To fall in line with other similar autcomplete functions in other projects, I wanted to request that the tab key key press act the same as the enter key. I believe a new case for Tab in this case switch chain: https://github.com/lekoala/bootstrap5-autocomplete/blob/master/autocomplete.js#L572 would do the trick. Thanks!

**Comment by lekoala** [comment]
i'm not entirely sure that "tab=enter" is the best practise here

take for example: https://jqueryui.com/autocomplete/ , which implements a lot of best practises, and it doesn't do that. tab is really expected to tab between elements from a user perspective. it gets worse when you tab between fields and one of them is an autocomplete that opens automatically : tab tab tab=> you select an item. not ideal

do you have an example in mind where this works like you describe?

**Comment by zach-st** [comment]
Hello, our use-case is along the lines of a "mention" where the user begins typing `@xyz` and the autocomplete populates with a list of items matching. I would love to see this functionality! Discord, Slack, and even MS Teams allow for tab selection from the autocomplete list (usernames, channels). Also [bootstrap datalists](https://getbootstrap.com/docs/5.3/forms/form-control/#datalists) seem to support the "select by tab" workflow.

**Comment by lekoala** [comment]
ok i see

i've put this behind a new config flag because it's still annoying to have the tab between fields blocked if you have autoselect first

https://github.com/lekoala/bootstrap5-autocomplete/releases/tag/1.1.31

other than that it should work as expected

bootstrap datalists don't select on tab for me (i don't think they should). in discord it makes more sense, because you need to trigger the menu first using a command key like @ and therefore it's ok to use the tab key for that
also, enter would send a message^^

**Comment by bwhartlove** [comment]
Will test this out and give it a try. Thank you!

**Comment by bwhartlove** [comment]
This worked out on my end. Thank you for the quick turnaround on the feature!
