### ISSUE TITLE
Feature request: option to keep items order (prevent sorting)

### ISSUE THREAD

**Issue by dejan-ant** [lekoala/bootstrap5-autocomplete#52]
Thank you for all the work on this project, it is awesome.

I would like to ask for the option to keep the natural order of items from remote source. For example, my search service is based on similarity with the query and the order of returned records is important. However, they are always shown sorted in ascending order in the dropdown list. It would be great to have an option to preserve the original order. Many thanks in advance!

**Comment by lekoala** [comment]
i don't apply any sorting so i'm a bit surprised by this

if you try on the demo you can see that the first entry returned is the one provided by the server

![image](https://github.com/user-attachments/assets/b4210ab0-4cc8-42a5-9754-4168a0335300)

**Comment by cheesengho** [comment]
Hello @lekoala. First of all, thank you for all your work on this project.

Actually, I had the similar issue as dejan mentioned and I found out that it was because of how this package uses `value` as the object's key. If I use number as value, it will be **assigned as an index instead string-key**, which will then be sorted like a normal index would.

For example, if my data returns `[3,1,2]`, it would be sorted as `[1,2,3]`. Attached with example if my words doesn't make sense

![image](https://github.com/user-attachments/assets/cbcfe9f7-b052-4c18-a212-30f014a890ca)

**Comment by lekoala** [comment]
oh i see you are completely right
i should have been using a regular array as the data source for a long time anyway so this is a long overdue fix

https://github.com/lekoala/bootstrap5-autocomplete/releases/tag/1.1.32
you can give this a go it seems to work fine as far as I can tell :)

**Comment by dejan-ant** [comment]
Hello cheesengho, thank you for figuring this out. Exactly that was my problem as well, if values are non-numeric everything is fine. 
Thank you lekoala for your prompt response!
